# Jekyll configuration
# see http://jekyllrb.com/docs/configuration/

# Jekyll excludes dot-files such as .gitignore oder .idea by default,
# but we need to exclude some more files
exclude: ['Gemfile*','*.iml','README.md']
